name: ROB GRUNDEN
favicon: null
layout_spectrum: 0.3271910985931754
typography_spectrum: 0.6404494496528059
title: 'Disciple | Missionary | Speaker | Writer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f6da'
    - '#363749'
    - '#6b6d55'
    - '#bab36f'
    - '#b64f4c'
  brandStrength: 0.1875
  lightness: 0.24909499450586736
  saturation: 0.7675985943060368
  rhythmicContrast: 0.3033513107802719
purpose: []
