name: ROBGRUNDEN
favicon: null
layout_spectrum: 0.3271910985931754
typography_spectrum: 0.6404494496528059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8859558156691492
  lightness: 0.24909499450586736
  saturation: 0.7675985943060368
  rhythmicContrast: 0.3033513107802719
purpose: []
